GoLogData/Controllers/DataModelController.cs
using GoLogData.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using GoLogData.Models;

namespace GoLogData.Controllers
{
    public class DataModelController : Controller
    {
        private readonly ApplicationDbContext _context;
        public DataModelController(ApplicationDbContext context)
        {
            _context = context;
        }



        // GET: DataModelController
        public ActionResult Index()
        {
            return View();
        }

        // GET: DataModelController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        public ActionResult AddModel(Guid id)
        {
            return View();
        }
        public ActionResult AddData(Guid id)
        {
            return View();
        }
        
       public async Task<IActionResult> CreateDataCell(string input, Guid modelId) 
       {
            //what do we need to create datacell? input and maybe the datamodelId
            if (ModelState.IsValid)
            {
                
                await using(var context = _context)
                {
                    //DataModel query = (DataModel)(from dm in context.DataModels
                    //                              where dm.ModelId == modelId
                    //                              select dm);
                    DataModel x = context
                        .ParentViewModels
                        .Where(u=>u.DataModel.ModelId == modelId)
                        .Select(u => u.DataModel)
                        .SingleOrDefault();
                    var newDataCell = new Datacell()
                    {
                        input = input,
                        Id = Guid.NewGuid(),
                        //get data from database where datamodle = modelId
                        DataModel = x // making issues
                    };
                    context.Add(newDataCell);
                    await context.SaveChangesAsync();
                    return RedirectToAction("Index", "DataBooks");
                }

            }
            return View();
       }

        // GET: DataModelController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DataModelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DataModelController/Edit/5
        public ActionResult Edit(Guid id)
        {
            return View();
        }

        // POST: DataModelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DataModelController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DataModelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

GoLogData/Controllers/ParentViewModelController.cs
using GoLogData.Data;
using GoLogData.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GoLogData.Controllers
{
    public class ParentViewModelController : Controller
    {

        private readonly ApplicationDbContext _context;
        public ParentViewModelController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: HomeController1
        public async Task<IActionResult> Index()
        {
            return View(await _context.ParentViewModels.ToListAsync());
            // return View();
        }

        // GET: HomeController1/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HomeController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ParentViewModel parentViewModel)
        {
            if (ModelState.IsValid)
            {
                parentViewModel.ParentViewModelId = Guid.NewGuid();
                parentViewModel.Databook = new Databooks()
                {
                    MultipleModels = false,
                    Title = parentViewModel.Databook.Title,
                    
                    Description = parentViewModel.Databook.Description
                };
                //every databook to have a default basic datamodel
                parentViewModel.DataModel = new DataModel()
                {
                    Databooks = parentViewModel.Databook,
                    Title = "default",
                    Label = "default label",
                    Description = "This is the default data model",
                    ModelId = Guid.NewGuid()

                };
                
                //_context.Add(parentViewModel.Databook);
                //_context.Add(parentViewModel.DataModel);
                _context.Add(parentViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Databooks");
            }
            return View(parentViewModel);
        }

        // GET: HomeController1/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            
           

            await using (var context = _context)
            {
                var query = from dm in context.DataModels
                            where dm.Databooks.Id == id 
                            select dm;
                
                //var query2 = from dc in context.Datacell
                //             where dc.DataModel == query.FirstOrDefault()
                //             select dc;
                //this isnt working for some reason, error says  
                //get DataModel where datamodel.DatabookId = id 
                List < DataModel > answer = query.ToList<DataModel>();
                //List<Datacell> datacells = query2.ToList<Datacell>();


                //ViewData["Datacells"] = datacells;
                ViewData["dataModels"] = answer;
                ViewData["DatabookId"] = id;

            }
            

            
            return View();
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController1/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult AddData(Guid modelId)
        {
            return View();
        }
        public ActionResult AddModel()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddModel(Guid Id, DataModel dm)
        {
            //create new model based on inputs and databookId
            //this is getting called as soon as page loads cause validaton to be off
            
                
                await using(var context = _context)
                {
                    Databooks x = context
                        .ParentViewModels
                        .Where(u=>u.Databook.Id == Id)
                        .Select(u=>u.Databook)
                        .SingleOrDefault(); // turning the databook Id passed into a databook object


                    DataModel addedModel = new DataModel()
                    {
                        ModelId = Guid.NewGuid(),
                        Databooks = x, 
                        Label = dm.Label,
                        Title = dm.Title,
                        Description = dm.Description,
                    };
                    _context.Add(addedModel);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index", "DataBooks");
            

            //save to database 
            
        }
        
    }
}

GoLogData/Views/ParentViewModel/AddModel.cshtml
@model GoLogData.Models.DataModel

@{
    ViewData["Title"] = "Add";
}

<h1>Edit</h1>

<h4>DataModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="AddModel" asp-controller="ParentViewModel">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Label" class="control-label"></label>
                <input asp-for="Label" class="form-control" />
                <span asp-validation-for="Label" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ModelId" />
            <div class="form-group">
                <input type="submit" value="AddModelToDatabase" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GoLogData/Views/ParentViewModel/Create.cshtml
@model GoLogData.Models.ParentViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create a new databook</h1>

<hr />
<div class="row">
    <div class="col-md-4">  
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label style="font-bold" asp-for="Databook.Title"></label>
                <br />
                <input asp-for="Databook.Title" />
                <span asp-validation-for="Databook.Title"></span>
                <br />
                
                <label style="font-bold" asp-for="Databook.Description"></label>
                <br />
                
                <textarea asp-for="Databook.Description" rows="10" cols="30"></textarea>
                <span asp-validation-for="Databook.Description"></span>
                <br />
                
                
                
                
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoLogData/Views/ParentViewModel/Delete.cshtml
@model GoLogData.Models.Databooks

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Databook</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GoLogData/Views/ParentViewModel/Details.cshtml
@model GoLogData.Models.Databooks

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Databook</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GoLogData/Views/ParentViewModel/Edit.cshtml
@using GoLogData.Data
@using Microsoft.Data.SqlClient
@using Microsoft.EntityFrameworkCore.Storage
@model GoLogData.Models.ParentViewModel


@{
    //cast viewdata as list
    var dataModelList = ViewData["dataModels"] as List<DataModel>;
    var databookId = ViewData["DatabookId"];
    //var dataCellList = ViewData["Datacells"] as List<Datacell>;

}
<div>
    <h1>Edit</h1>
    <div style="right: 150px">
        <a asp-controller="ParentViewModel" asp-action="AddModel"  asp-route-id="@databookId">Add a new DataModel</a>

    </div>
</div>

<h4>Databook</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <table class="table">
                <thead>DataModels</thead>
                <tbody>
                   @foreach (var item in dataModelList)
                   {
                     <tr>
                       <td>@item.Label</td>
                       <td>@item.Description</td>
                       <td>
                           <a class="btn btn-primary" asp-controller="DataModel" asp-action="AddData" asp-route-id="@item.ModelId">Add</a>
                           <a class="btn btn-danger" asp-controller="DataModel" asp-action="Delete">Delete</a>
                           
                       </td>
                     </tr>
                   }

                </tbody>
            </table>


            <!--
            <input type="hidden" asp-for="Databook.Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <button type="button"  class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#newModelModal">New Data Model<script>console.log("clicked");</script></button>
            </div>
            -->
        </form>
    </div>
</div>
<!--
<div>
    <table class="table">
        <thead>DataCell for current Datamodel</thead>
        <tbody>
           @* @foreach(var item in dataCellList)
            {
                <tr>
                    <td>@item.input</td>
                </tr>

            }*@
              
            
        </tbody>
    </table>
</div>
-->
<!--
<div class="modal fade" id="newModelModal" tabindex="-1" role="dialog" aria-labelledby="newModelModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newModelModalLabel">Create A New Model</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="body" id="modalBody">
                <form method="post"  asp-action="Create">
                    <div class="form-group">
                        <br />
                        <label style="font-bold" asp-for="DataModel.Title">DataModel Title</label>
                        <br />
                        <input asp-for="DataModel.Title" />
                        <span asp-validation-for="DataModel.Title"></span>
                        <br />
                        <label style="font-bold"  asp-for="DataModel.Description"></label>
                        <br />
                        <input asp-for="DataModel.Description" />
                        <span asp-validation-for="DataModel.Description"></span>
                    </div>
                </form>
                
            </div>
            <div class="modal-footer">
                
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" asp-controller="DataModel" value="Create" class="btn btn-primary">Create Model</button>
            </div>
        </div>
    </div>
</div>
-->

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GoLogData/Views/ParentViewModel/Index.cshtml
@model IEnumerable<GoLogData.Models.ParentViewModel>
@inject IHttpContextAccessor http;

@{
    ViewData["Title"] = "Index";
    
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <!--
        <div class="card-deck">
            //foreach (var item in Model) {             
            //    <div class="card">

                </div>
                
            }
            <div class="card" style="width: 18rem; height: 18rem;">
                <div class="card-header">New Databook</div>
                
                <div class="card-body">
                    <div class="card-text" style="text-align: center;">
                        <h5 >Create new Databook</h5>
                        <a asp-action="Create">
                            <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" fill="currentColor" class="bi bi-plus-square-dotted" viewBox="0 0 16 16" >
                                 <path d="M2.5 0c-.166 0-.33.016-.487.048l.194.98A1.51 1.51 0 0 1 2.5 1h.458V0H2.5zm2.292 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zm1.833 0h-.916v1h.916V0zm1.834 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zM13.5 0h-.458v1h.458c.1 0 .199.01.293.029l.194-.981A2.51 2.51 0 0 0 13.5 0zm2.079 1.11a2.511 2.511 0 0 0-.69-.689l-.556.831c.164.11.305.251.415.415l.83-.556zM1.11.421a2.511 2.511 0 0 0-.689.69l.831.556c.11-.164.251-.305.415-.415L1.11.422zM16 2.5c0-.166-.016-.33-.048-.487l-.98.194c.018.094.028.192.028.293v.458h1V2.5zM.048 2.013A2.51 2.51 0 0 0 0 2.5v.458h1V2.5c0-.1.01-.199.029-.293l-.981-.194zM0 3.875v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 5.708v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 7.542v.916h1v-.916H0zm15 .916h1v-.916h-1v.916zM0 9.375v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .916v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .917v.458c0 .166.016.33.048.487l.98-.194A1.51 1.51 0 0 1 1 13.5v-.458H0zm16 .458v-.458h-1v.458c0 .1-.01.199-.029.293l.981.194c.032-.158.048-.32.048-.487zM.421 14.89c.183.272.417.506.69.689l.556-.831a1.51 1.51 0 0 1-.415-.415l-.83.556zm14.469.689c.272-.183.506-.417.689-.69l-.831-.556c-.11.164-.251.305-.415.415l.556.83zm-12.877.373c.158.032.32.048.487.048h.458v-1H2.5c-.1 0-.199-.01-.293-.029l-.194.981zM13.5 16c.166 0 .33-.016.487-.048l-.194-.98A1.51 1.51 0 0 1 13.5 15h-.458v1h.458zm-9.625 0h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zm1.834-1v1h.916v-1h-.916zm1.833 1h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
                            </svg>
                        </a>
                    </div>
                    

                </div>
            </div>
        </div>

        </>
         -->
          
  <table>
      <tbody>
          @{
              string previousUrl = http.HttpContext.Request.Path;
              
          }
          @foreach (ParentViewModel parentViewModel in Model)
          {
              //QUERY DATABASE for databook with parentViewModel.DatabookId 
              //string query = "Select Databook.Title, Databook.Description From Databook Where Databook.Id = " + parentViewModel.D
               <tr>
                   <td>@parentViewModel.Databook.Title</td>
                   <td>@parentViewModel.Databook.Description</td>
                   <td>
                       <a class="btn btn-primary" asp-route-id="@parentViewModel.Databook.Id" asp-route-previousUrl="@previousUrl" asp-Controller="" asp-action="">View Databook</a>
                       <a class="btn btn-secondary" asp-route-id="@parentViewModel.Databook.Id" asp-action="Edit">Edit Databook</a>
                       <a class="btn btn-danger" asp-route-id="@parentViewModel.Databook.Id" asp-action="Delete">Delete Databook</a>
                   </td>
               </tr>   
          }
       
         
          
    </tbody>
</table>
<div>
    <a asp-action="Create">Add</a>
</div>